project:
  output-dir: ../../docs
  type: website
  render:
    - "*.qmd"

website:
  page-navigation: true
  back-to-top-navigation: true
  title: "PyMARC en Español"
  navbar:
    # style: docked
    # background: primary
    search: false
    left:
      - text: Taller Introductorio PyMARC
        menu:
          - 01_introduccion.qmd
          - 02_introduccion_python.qmd
          - 03_introduccion_pymarc.qmd
          - 04_introduccion_pymarc2.qmd
          - 05_introduccion_pymarc3.qmd
          - 06_introduccion_pymarc4.qmd
  sidebar:
    - id: taller-00
      search: false
      title: "Taller Introductorio PyMARC"
      style: "docked"
      background: light
      contents:
        - 01_introduccion.qmd
        - 02_introduccion_python.qmd
        - 03_introduccion_pymarc.qmd
        - 04_introduccion_pymarc2.qmd
        - 05_introduccion_pymarc3.qmd
        - 06_introduccion_pymarc4.qmd

sidebar: false

format:
  html:
    theme: yeti
    toc: true
    css: css/output.css
