project:
  output-dir: ../../public/_episodes
  type: website
  render:
    - "*.qmd"

website:
  navbar:
    # style: docked
    # background: primary
    search: false
    left:
      - index.qmd
      - text: Taller Introductorio PyMARC
        menu:
          - 01_introduccion.qmd
          - 02_introduccion_python.qmd
          - 03_introduccion_pymarc.qmd
          - 04_introduccion_pymarc2.qmd
          - 05_introduccion_pymarc3.qmd
          - 06_introduccion_pymarc4.qmd

format:
  html:
    theme: cosmo 
    toc: true
    css: css/output.css
